/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHasOwnable,
  IHasOwnableInterface,
} from "../../../contracts/interfaces/IHasOwnable";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IHasOwnable__factory {
  static readonly abi = _abi;
  static createInterface(): IHasOwnableInterface {
    return new Interface(_abi) as IHasOwnableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IHasOwnable {
    return new Contract(address, _abi, runner) as unknown as IHasOwnable;
  }
}
