/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAssetHandler {
  export type AssetStruct = {
    asset: AddressLike;
    assetType: BigNumberish;
    aggregator: AddressLike;
  };

  export type AssetStructOutput = [
    asset: string,
    assetType: bigint,
    aggregator: string
  ] & { asset: string; assetType: bigint; aggregator: string };
}

export interface AssetHandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAsset"
      | "addAssets"
      | "assetTypes"
      | "chainlinkTimeout"
      | "getUSDPrice"
      | "initialize"
      | "owner"
      | "priceAggregators"
      | "removeAsset"
      | "renounceOwnership"
      | "setChainlinkTimeout"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddedAsset"
      | "Initialized"
      | "OwnershipTransferred"
      | "RemovedAsset"
      | "SetChainlinkTimeout"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAsset",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAssets",
    values: [IAssetHandler.AssetStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assetTypes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "chainlinkTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUSDPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [IAssetHandler.AssetStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceAggregators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setChainlinkTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAsset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addAssets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetTypes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainlinkTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUSDPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceAggregators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainlinkTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AddedAssetEvent {
  export type InputTuple = [
    asset: AddressLike,
    assetType: BigNumberish,
    aggregator: AddressLike
  ];
  export type OutputTuple = [
    asset: string,
    assetType: bigint,
    aggregator: string
  ];
  export interface OutputObject {
    asset: string;
    assetType: bigint;
    aggregator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemovedAssetEvent {
  export type InputTuple = [asset: AddressLike];
  export type OutputTuple = [asset: string];
  export interface OutputObject {
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetChainlinkTimeoutEvent {
  export type InputTuple = [_chainlinkTimeout: BigNumberish];
  export type OutputTuple = [_chainlinkTimeout: bigint];
  export interface OutputObject {
    _chainlinkTimeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetHandler extends BaseContract {
  connect(runner?: ContractRunner | null): AssetHandler;
  waitForDeployment(): Promise<this>;

  interface: AssetHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAsset: TypedContractMethod<
    [asset: AddressLike, assetType: BigNumberish, aggregator: AddressLike],
    [void],
    "nonpayable"
  >;

  addAssets: TypedContractMethod<
    [assets: IAssetHandler.AssetStruct[]],
    [void],
    "nonpayable"
  >;

  assetTypes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  chainlinkTimeout: TypedContractMethod<[], [bigint], "view">;

  getUSDPrice: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  initialize: TypedContractMethod<
    [assets: IAssetHandler.AssetStruct[]],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  priceAggregators: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  removeAsset: TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setChainlinkTimeout: TypedContractMethod<
    [newTimeoutPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAsset"
  ): TypedContractMethod<
    [asset: AddressLike, assetType: BigNumberish, aggregator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addAssets"
  ): TypedContractMethod<
    [assets: IAssetHandler.AssetStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assetTypes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "chainlinkTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUSDPrice"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [assets: IAssetHandler.AssetStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceAggregators"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "removeAsset"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setChainlinkTimeout"
  ): TypedContractMethod<
    [newTimeoutPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AddedAsset"
  ): TypedContractEvent<
    AddedAssetEvent.InputTuple,
    AddedAssetEvent.OutputTuple,
    AddedAssetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RemovedAsset"
  ): TypedContractEvent<
    RemovedAssetEvent.InputTuple,
    RemovedAssetEvent.OutputTuple,
    RemovedAssetEvent.OutputObject
  >;
  getEvent(
    key: "SetChainlinkTimeout"
  ): TypedContractEvent<
    SetChainlinkTimeoutEvent.InputTuple,
    SetChainlinkTimeoutEvent.OutputTuple,
    SetChainlinkTimeoutEvent.OutputObject
  >;

  filters: {
    "AddedAsset(address,uint16,address)": TypedContractEvent<
      AddedAssetEvent.InputTuple,
      AddedAssetEvent.OutputTuple,
      AddedAssetEvent.OutputObject
    >;
    AddedAsset: TypedContractEvent<
      AddedAssetEvent.InputTuple,
      AddedAssetEvent.OutputTuple,
      AddedAssetEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RemovedAsset(address)": TypedContractEvent<
      RemovedAssetEvent.InputTuple,
      RemovedAssetEvent.OutputTuple,
      RemovedAssetEvent.OutputObject
    >;
    RemovedAsset: TypedContractEvent<
      RemovedAssetEvent.InputTuple,
      RemovedAssetEvent.OutputTuple,
      RemovedAssetEvent.OutputObject
    >;

    "SetChainlinkTimeout(uint256)": TypedContractEvent<
      SetChainlinkTimeoutEvent.InputTuple,
      SetChainlinkTimeoutEvent.OutputTuple,
      SetChainlinkTimeoutEvent.OutputObject
    >;
    SetChainlinkTimeout: TypedContractEvent<
      SetChainlinkTimeoutEvent.InputTuple,
      SetChainlinkTimeoutEvent.OutputTuple,
      SetChainlinkTimeoutEvent.OutputObject
    >;
  };
}
